### ISSUE TITLE
Excellent Crates Support

### ISSUE THREAD

**Issue by ElTuna** [bloodmc/GDHooks#12]
Hi! I am using [Excellent Crates](https://www.spigotmc.org/resources/excellentcrates-advanced-custom-crates.48732/) and users need container trust to be able to open the crate (using right click) but they still arent able to preview the crate content (because it needs left click)
i was trying to do it allowing `interact-block-primary` and `block-break` flags but plugin said i don't have perms to use that flags...
anyways i need support for Excellent Crates for it to be easy :c

images here:
[can't interact](https://cdn.discordapp.com/attachments/678797601042333726/967535908175872030/unknown.png)
[can't use flags](https://cdn.discordapp.com/attachments/678797601042333726/967540037644320818/unknown.png)

**Comment by bloodmc** [comment]
Can you provide a GD debug of the actions with crates that do not work?
Follow the link here
https://github.com/bloodmc/GriefDefender/wiki/Debugging

When finished, provide the debug link it generates.

**Comment by bloodmc** [comment]
Added in commit
https://github.com/bloodmc/GDHooks/commit/f91daaba5f4cf7b46a0eb321cb99997ae710097f
