### ISSUE TITLE
Suggestion: support for oraxen elements

### ISSUE THREAD

**Issue by marlon233-omc** [bloodmc/GDHooks#13]
Hello I have a suggestion for **GDHook**

**Suggestion:**
Add oraxen item support to be able to place oraxen items in **inspection-tool=** and **modification-tool=**

Why?
My server has several oraxen custom items and I would like to be able to use oraxen items in GD to further customize the plugin and make it different from other servers.

**Comment by bloodmc** [comment]
Added in commit 
https://github.com/bloodmc/GDHooks/commit/4af2a0382e3d24c884898e55a5646f2f5ee8dac3
