### ISSUE TITLE
Visual bug with SIMPLECLANS

### ISSUE THREAD

**Issue by Darkmager** [bloodmc/GDHooks#16]
using gd hooks bukkit 0.8 DEV3

HOW TO REPRODUCE:
Install Simple clans latest
allow permission in your claimed area by simple clan command /clan land allow/block (function)
it works but gd shows you can't be able to break/place/interact

**Comment by bloodmc** [comment]
This is a SimpleClans command which requires integration on their side. For GDHooks, use /clantrust tag
