### ISSUE TITLE
build error circular dependency

### ISSUE THREAD

**Issue by WR8187** [bloodmc/GDHooks#2]
Circular dependency between the following tasks:
:bukkit:classes
\--- :bukkit:compileJava
     \--- :common:loader-utils:shadowJar
          \--- :bukkit:shadowJar
               \--- :bukkit:classes (*)

**Comment by sarhatabaot** [comment]
This happens because the shadowjar task of loader-utils depends on the bukkit module's shadowjar.

**Comment by WR8187** [comment]
I'm kinda new with gradle how would I build the project without getting this error?

**Comment by bloodmc** [comment]
Fixed in dev branch. Will be merged to master after GD 2.1.0 release.
