### ISSUE TITLE
The subclaims are not reflected in the Pl3xmap

### ISSUE THREAD

**Issue by Skjolberg** [bloodmc/GDHooks#5]
I have a problem with GDHooks in 1.17.1, the subclaims are not reflected in the Pl3xmap, in 1.16.5 it works without problem, I just realized it now because my creative server is not usually played and I wanted to test things and I found this, you can try it yourselves to see if it works for you or not. When I make them they appear on the map but when I restart the server it only shows the city and the basic claim, but the subclaim does not appear, everything I say is visually on the map, the subclaim is created without problem, GriefDefender works very well.

Thanks

**Comment by bloodmc** [comment]
GDHooks 0.6 will support Squaremap instead of Pl3xmap as it is no longer maintained.
