### ISSUE TITLE
How do I use this? Where is the file I need?

### ISSUE THREAD

**Issue by Possemaster** [bloodmc/GDHooks#6]
I don't understand how to use this. I have bought GriefDefender, I have Dynmap. Claims do not show up so I guess the GDHookls is not default with Griefdefender. It leads me here, but i can only download the source code. What do I do with it?
I tried running the batch file but it always shows a red error.

**Comment by bloodmc** [comment]
GDHooks is available on discord. You can also build it the jar yourself using git.
